### ISSUE TITLE
近期官方的API是否有变更？

### ISSUE THREAD

**Issue by kkkgo** [DNSPod/dnspod-api-doc#4]
先是返回来的json格式有变，然后今天发现（多人发现和测试）是带UA参数的请求都会被403，不带UA的反而不会。

**Comment by kkkgo** [comment]
来自API文档的第5条：
关于UserAgent：
请求的时候必须设置UserAgent，如果不设置或者设置为不合法的（比如设置为浏览器的）也会导致帐号被封禁API。
UserAgent的格式必须为：程序英文名称/版本(联系邮箱)，比如：MJJ DDNS Client/1.0.0 (shallwedance@126.com)。

**Comment by PrintNow** [comment]
我也遇到了，至今都未解决...
